# Generated by Django 3.2.11 on 2022-01-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('have_to_do', 'Have To Do'), ('working_now', 'Working Now'), ('blocked', 'Blocked'), ('done', 'Done')], default='have_to_do', max_length=255),
        ),
    ]
